"use client";
import { useState } from "react";
import Link from "next/link";
import { createAudit, userFacingApiError } from "../lib/api";
import { isClearlyCiscoConfiguration } from "../lib/vendor-detection";
import type { AuditReport } from "../lib/types";
import ReportView from "../components/audit/ReportView";

const demo = "aaa new-model\nip ssh version 1\nip ssh time-out 120\nline vty 0 4\n transport input telnet\n";
export default function Home() {
  const [vendor, setVendor] = useState("auto"); const [configuration, setConfiguration] = useState(""); const [report, setReport] = useState<AuditReport | null>(null); const [auditId, setAuditId] = useState<string | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function runAudit() { if (!configuration.trim()) { setError("Paste a configuration before running the audit."); return; } if (vendor === "auto" && !isClearlyCiscoConfiguration(configuration)) { setError("Auto Detect could not identify a supported Cisco IOS / IOS-XE configuration. Select Cisco explicitly or provide clearer Cisco syntax."); return; } if (vendor !== "auto" && vendor !== "cisco") { setError("Multi-vendor semantic integration is being finalized. Cisco audit is currently available in the prototype."); return; } setError(""); setLoading(true); setReport(null); try { const result = await createAudit(configuration); setReport(result.report); setAuditId(result.audit_id); } catch (err) { setError(userFacingApiError(err)); } finally { setLoading(false); } }
  const lineCount = configuration ? configuration.split(/\r?\n/).length : 0;
  return <><section className="hero"><span className="eyebrow">Security operations · workspace</span><h1>AI-Driven Multi-Vendor Network Security Compliance Auditor</h1><p>Evidence-backed configuration analysis and defensive attack-path modeling.</p><div className="workspace-status"><span>SYSTEM ONLINE</span><small>Cisco IOS / IOS-XE audit path available</small></div></section><div className="workspace-grid"><section className="panel"><div className="panel-heading"><span className="eyebrow">New security audit</span><span className="meta">Local-first analysis</span></div><label className="label" htmlFor="vendor">Vendor / platform</label><select id="vendor" className="select" value={vendor} onChange={e => setVendor(e.target.value)}><option value="auto">Auto Detect</option><option value="cisco">Cisco IOS / IOS-XE</option><option value="juniper">Juniper Junos</option><option value="fortigate">FortiGate</option></select><label className="label" htmlFor="configuration" style={{ marginTop: 22 }}>Configuration</label><textarea id="configuration" className="textarea" value={configuration} onChange={e => setConfiguration(e.target.value)} placeholder="Paste network device configuration here..." /><div className="input-meta">{configuration.length} characters · {lineCount} lines</div>{error && <div className="notice error" role="alert">{error}</div>}<div className="actions"><button className="button primary" onClick={runAudit} disabled={loading}>{loading ? "Analyzing configuration…" : "Run Security Audit"}</button><button className="button" onClick={() => { setConfiguration(""); setReport(null); setError(""); }} disabled={loading}>Clear</button><button className="button" onClick={() => setConfiguration(demo)} disabled={loading}>Load demo</button></div></section><aside className="panel"><span className="eyebrow">Audit pipeline</span><p className="meta" style={{ lineHeight: 1.6 }}>AI/semantic interpretation assists normalization. Deterministic rules make compliance decisions.</p><div className="pipeline-steps">{["Configuration", "Vendor Parser", "Semantic Normalization", "SecurityFact", "Compliance Engine", "Evidence & Risk", "Attack Scenarios", "Human Review"].map((stage, index) => <div key={stage}><b>{String(index + 1).padStart(2, "0")}</b><span>{stage}</span></div>)}</div></aside></div>{report && <><div className="section-title"><h2>Audit result</h2>{auditId && <Link className="button" href={`/audits/${auditId}`}>Open persisted report →</Link>}</div><ReportView report={report} /></>}</>;
}
