import type { AuditReport } from "../../lib/types";
import { calculateSeverityDistribution } from "../../lib/severity-distribution";
import FindingList from "./FindingList";
import AttackScenarios from "./AttackScenarios";

export default function ReportView({ report, auditId }: { report: AuditReport; auditId?: string }) {
  const { summary, posture } = report;
  const metrics = [["CONTROLS", summary.total_controls], ["PASSED", summary.passed], ["FAILED", summary.failed], ["MANUAL", summary.manual], ["CRITICAL", summary.critical_count], ["HIGH", summary.high_count], ["MEDIUM", summary.medium_count], ["LOW", summary.low_count], ["PENDING", summary.review_pending_count], ["REVIEWED", summary.review_completed_count]];
  const distribution = calculateSeverityDistribution(report.findings);
  const severity = [["Critical", distribution.CRITICAL], ["High", distribution.HIGH], ["Medium", distribution.MEDIUM], ["Low", distribution.LOW]];
  const scenarios = report.attack_scenarios ?? [];
  return <section>{posture && <div className="panel posture-card"><span className="eyebrow">Security posture score</span><div className="posture-score">{posture.score}<small>/100</small></div><p className="meta">{posture.rating} · Backend-calculated, deterministic score</p><div className="posture-breakdown"><span>Passed <b>{posture.passed}</b></span><span>Failed <b>{posture.failed}</b></span><span>Manual <b>{posture.manual}</b></span><span>Deductions <b>{posture.deductions.reduce((total, item) => total + item.deduction, 0)}</b></span></div><p className="meta">{posture.explanation}</p><div className="posture-deductions">{posture.deductions.map(item => <span key={`${item.rule_id}-${item.deduction}`}>{item.rule_id} · {item.severity} · -{item.deduction}</span>)}</div></div>}<div className={`status-card ${summary.overall_status}`}><div className="result-hero"><div><span className="eyebrow">Audit summary · deterministic result</span><div className="status">{summary.overall_status.replace("_", " ")}</div><p className="meta">{summary.failed} failed · {summary.manual} manual · {summary.passed} passed</p></div><div className="summary-ring"><strong>{summary.total_controls}</strong><span>controls</span></div></div><div className="summary-grid">{metrics.map(([label, value]) => <div className="metric" key={label as string}><span className="label">{label}</span><strong>{value}</strong></div>)}</div><div className="severity-strip"><span className="label">Severity distribution</span>{severity.map(([label, value]) => <div className="severity-row" key={label as string}><span>{label}</span><div><i style={{ width: `${report.findings.length ? Number(value) / report.findings.length * 100 : 0}%` }} /></div><strong>{value}</strong></div>)}</div><p className="meta architecture-note">Semantic interpretation assists normalization. Deterministic rules make compliance decisions.</p></div><AttackScenarios scenarios={scenarios} /><div className="section-title"><h2>Findings</h2><span className="meta">{report.findings.length} controls evaluated</span></div><FindingList findings={report.findings} auditId={auditId} /></section>;
}
